# Generated by Django 2.2.6 on 2020-01-29 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('release_date', models.DateTimeField(verbose_name='release date')),
                ('availability', models.BooleanField()),
                ('description', models.CharField(max_length=1024)),
                ('series', models.CharField(max_length=250)),
                ('vol_num', models.IntegerField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_bookstore_app.AuthorsList')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_bookstore_app.Book')),
            ],
        ),
    ]
