# Generated by Django 3.0.2 on 2020-01-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_bookstore_app', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
