# Generated by Django 3.0.2 on 2020-02-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bookstore_app', '0003_auto_20200206_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='vol_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
