# Generated by Django 3.0.2 on 2020-02-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bookstore_app', '0005_auto_20200207_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='vol_num',
            field=models.IntegerField(blank=True),
        ),
    ]
