# Generated by Django 3.0.3 on 2020-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bookstore_app', '0013_auto_20200207_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.CharField(default='eng', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='AuthorsList',
        ),
    ]
